Repository berty/go-libtor, pull requests merged in 2020-11, with the labels that each got.

#2 ci: no verbose
  .github/workflows/update.yaml
Labels: ci, 🔍 Ready for Review

#3 feat: build ios static libs on Github Actions
  .github/workflows/ios_libs.yml
  build/VERSIONS
  build/scripts/configure-ios.sh
  build/scripts/openssl-build-ios/.gitignore
  build/scripts/openssl-build-ios/CREDITS
  build/scripts/openssl-build-ios/LICENSE-APACHE
  build/scripts/openssl-build-ios/LICENSE-OPENSSL
  build/scripts/openssl-build-ios/build-libssl.sh
  build/scripts/openssl-build-ios/config/20-ios-tvos-cross.conf
  build/scripts/openssl-build-ios/scripts/build-loop-targets.sh
  build/scripts/openssl-build-ios/template/opensslconf-template.h
Labels: enhancement, 🔍 Ready for Review

#4 fix: ios static libs release job
  .github/workflows/ios_libs.yml
Labels: bug, 🔍 Ready for Review
